apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - homepage/namespace.yaml
  - homepage/configmap.yaml
  - homepage/serviceaccount.yaml
  - homepage/deployment.yaml
  - homepage/service.yaml
