apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metallb/namespace.yaml
  - metallb/helmrelease.yaml
  - monitoring/prometheus-helmrelease.yaml
  - cloudflare-tunnel/namespace.yaml
  - cloudflare-tunnel/sealed-secret.yaml
  - cloudflare-tunnel/configmap.yaml
  - cloudflare-tunnel/deployment.yaml
