apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-tunnel-token
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    token: AgAzfV6d1rh/GQgKcoE/Jw4YUzKVqUcEUj1dVK6ohnAaMkwz6Lpw6fgSJ2STFmygtD7W6WRWu3mXTkqvPhi7vMpYUWT5+rNMwMPUpgdLI61ftrJVkBto7IA2XI6BjqmR8zw5z6CFYi5RbS7eE3QtjbeJstZkPDQUz9M/3ae06gH72SY7VhjIC+ExtPoGJYiwQmaYBqh7wEyZ035DyRdeG13kbZoivOvM7dWKWcvoYqr6AtibUL9OK23zEpWpTbl/80MPbb3dixm9Nwv8kSi+QPI4lBfTJGv4ig9Y92IRrpe0lgQFgSKxYtdQf5xVLJ/+RXhLyhTlj6Ma1zGqE/VPPT87Fqysi6Fr0q5F0bGpRn1nkgr8XI7E0QVB9nGS29oUW3Mnqcwv6amHpOGmdVF1TCEbckPav75hq7nLJQ9f9u7wT3F3ooNCh4iMioE0W2p73U5Z05tB9HOtmH+S2GYdumwMY6Qe5p+pOv9M+whsyi6Bz8tuv70Y+c4nxLjlskMYY41oqxWEJ7BYwf9EP05HMHwZeg8ocTliFkveoFaF20LoDa4PHblLbzOXJxIzuD+K/bbn2/F6yBofNXIo6rIA05lSOmuiFRaVadjsxm6fQxN0d0MLSh6IY+yAdWMKS/m44yf0Xo+FFr9VRFgzJ166z6dlrqlak+v/AlTAH4oKh0SFkZhHA0KxjYD80MU7ZmVX+T+jDrlom8kz3QF2B2PD2WNwdJwO1VfUBTKgNFrzNYq6Vjr/e2GGvlYC5euNzCsoexyGKw8P9tDzqSHxEd+jtKJHWXGWC6gaEYMcVX0gkdBH8wV/RwUq67N2UuwAawcPU9BqUvVTmCG3CLiPyOO6Uj3s8JcmnQmwP5XSA4ABfcOHMinyGmUud8lRYn3g8MszgcdXQzkHgrCkoYFNiCTTk7WTCW5jp4YQWETlEx3YwJlPUMkrxp4cquGU
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-tunnel-token
      namespace: cloudflare-tunnel
---
