apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  settings.yaml: |
    title: Homelab K8s
    theme: dark
    color: slate
  
  services.yaml: |
    - Services:
        - Grafana:
            icon: grafana.svg
            href: https://grafana.lab.ripcloud.io
            description: Metrics & Dashboards
        
        - Prometheus:
            icon: prometheus.svg
            href: https://prometheus.lab.ripcloud.io
            description: Metrics Collection
        
        - Demo:
            icon: nginx.svg
            href: https://demo.lab.ripcloud.io
            description: Demo Application
  
  widgets.yaml: ""
  bookmarks.yaml: ""
  docker.yaml: ""
  kubernetes.yaml: ""
  proxmox.yaml: ""
  custom.css: ""
  custom.js: ""
